"""baseline

Revision ID: a98b67b2a2a4
Revises: 
Create Date: 2026-09-08 13:51:00.153350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a98b67b2a2a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=mysql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'SHIPPED', 'DELIVERED'),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'SHIPPED', 'DELIVERED', 'EXPIRED', name='orderstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'SHIPPED', 'DELIVERED', 'EXPIRED', name='orderstatus'),
               type_=mysql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'SHIPPED', 'DELIVERED'),
               existing_nullable=False)
    # ### end Alembic commands ###
